# -*- coding: utf-8 -*-
{
    "name": "Advanced Property Sale & Rental Management",
    "summary": "Full Real Estate Suite: Sales, Rentals, Lease Contracts, Maintenance, and Landlord Portal.",
    "version": "18.0.1.0.0", # Standardized for Odoo 18
    "category": "Industry",
    "author": "Digital Hut Africa",
    "website": "https://www.diha.co.tz",
    "license": "OPL-1",
    
    # --- APP STORE PRICING ---
    "price": 999.00,        # Set your desired price
    "currency": "EUR",

    "description": """
Advanced Property Management for Odoo 18
========================================
A complete end-to-end solution for real estate companies, property managers, 
and landlords.

Key Features:
-------------
* **Property Sales & Rentals:** Manage the full lifecycle of property listings.
* **Lease Contracts:** Automated contract generation and expiry tracking.
* **Financial Management:** Recurring invoices for rent and utility bill management.
* **Maintenance:** Integrated maintenance request and equipment tracking.
* **Portals:** Dedicated portal for Landlords to track their property performance.
* **Reporting:** Advanced XLS reports for occupancy and sales.
""",
    "depends": [
        "base",
        "mail",
        "documents",
        "contacts",
        "account",
        "hr",
        "maintenance",
        "crm",
        "website",
        "frontdesk",
        "whatsapp",
    ],
    "data": [
        "security/groups.xml",
        "security/ir.model.access.csv",
        "security/security_update.xml",
        "security/security_manager.xml",
        "data/ir_cron.xml",
        "data/sequence.xml",
        "data/property_product_data.xml",
        "wizard/property_maintenance_wizard_view.xml",
        "wizard/contract_wizard_view.xml",
        "wizard/property_payment_wizard_view.xml",
        "wizard/extend_contract_wizard_view.xml",
        "wizard/property_vendor_wizard_view.xml",
        "wizard/booking_wizard_view.xml",
        "wizard/property_sale_tenancy_xls_report_view.xml",
        "wizard/landlord_tenancy_sold_xls_view.xml",
        "wizard/booking_inquiry_view.xml",
        "wizard/active_contract_view.xml",
        "wizard/utility_bill_register_wizard.xml",
        "wizard/property_terminate_wizard_view.xml",
        "wizard/invoice_xls_report_wizard_view.xml",
        "wizard/property_occupancy_xls_report_wizard_view.xml",
        "wizard/upload_utility_excel_wizard_view.xml",
        "wizard/utility_bill_send_views.xml",
        "wizard/agreement_template_preview_wizard_view.xml",
        "views/assets.xml",
        "views/property_details_view.xml",
        "views/property_document_view.xml",
        "views/user_type_view.xml",
        "views/contract_sub_stage_view.xml",
        "views/tenancy_details_view.xml",
        "views/contract_duration_view.xml",
        "views/rent_invoice_view.xml",
        "views/property_amenities_view.xml",
        "views/property_specification_view.xml",
        "views/property_vendor_view.xml",
        "views/certificate_type_view.xml",
        "views/parent_property_view.xml",
        "views/property_tag_view.xml",
        "views/product_product_inherit_view.xml",
        "views/property_invoice_inherit.xml",
        "views/res_config_setting_view.xml",
        "views/property_res_city.xml",
        "views/nearby_connectivity_view.xml",
        "views/agreement_template_view.xml",
        "views/meter_type.xml",
        "views/handover_property.xml",
        "views/utility_bill.xml",
        "views/maintenance_template_view.xml",
        "views/property_inspection.xml",
        "views/account_payment_inherit_view.xml",
        "views/maintenance_product_inherit.xml",
        "views/property_maintenance_view.xml",
        "views/property_crm_lead_inherit_view.xml",
        "views/maintenance_equipment_inherit_views.xml",
        "views/maintenance_equipment_category_inherit_views.xml",
        "report/report_invoice_template.xml",
        "report/tenancy_details_report_template.xml",
        "report/property_details_report.xml",
        "report/property_sold_report.xml",
        "report/lease_agreement_report.xml",
        "report/handover_property_report.xml",
        "report/utility_bill_report_template.xml",
        "report/utility_bill_report.xml",
        "report/commercial_lease_agreement_report.xml",
        "report/expiring_contract_list_report.xml",
        "report/equipment_qr_code_report.xml",
        "report/payment_receipt_report.xml",
        "data/active_contract_mail_template.xml",
        "data/tenancy_reminder_mail_template.xml",
        "data/property_book_mail_template.xml",
        "data/property_sold_mail_template.xml",
        "data/sale_invoice_mail_template.xml",
        "data/agreement_expiry_alert_mail_template.xml",
        "data/invoice_raise_alert_mail_template.xml",
        "data/payment_followup_alert_mail_template.xml",
        "data/expiring_contract_list.xml",
        "data/payment_prior_alert.xml",
        "data/maintenance_request_notification_mail_template.xml",
        "data/property_report_mails.xml",
        "data/utility_bill_mail_template.xml",
        "data/register_payment_mail_template.xml",
        "views/property_manager_view.xml",
        "views/templates/landlord_portal.xml",
        "views/menus.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "property_management/static/src/js/property_dashboard.js",
            "property_management/static/src/xml/property_dashboard.xml",
        ],
        "web.assets_frontend": [
            "property_management/static/src/js/portal.js",
            "property_management/static/src/css/lib/portal_style.css",
        ],
    },
    "images": [
        "static/description/banner.png", # Change from .gif to .png for better store display
    ],
    "installable": True,
    "application": True,
    "auto_install": False,
}