# -*- coding: utf-8 -*-
from . import contract_wizrd
from . import property_payment_wizard
from . import extend_contract_wizard
from . import property_vedor_wizard
from . import Property_maintenance_wizard
from . import booking_wizard
from . import property_sale_tenancy_xls_report
from . import landlord_tenancy_sold_xls
from . import booking_inquiry
from . import active_contract
from . import utility_bill_register
from . import property_terminate_wizard
from . import invoice_xls_report_wizard
from . import property_occupancy_xls_report
from . import upload_utility_excel_wizard
from . import utility_bill_send
from . import agreement_template_preview_wizard
from . import account_payment_register_inherit
